name: Phase 1 CI

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'test/**'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'test/**'

jobs:
  phase1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile with warnings and symbols
        run: gcc -Wall -Wextra -O2 -Iinclude -o portagens src/main.c src/read_files.c src/operations.c src/data.c
