name: C Project CI

# Dispara em pushes e pull-requests na main (ou outra branch)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile with optimization
      run: gcc -O2 -Iinclude -o portagens src/main.c src/read_files.c src/operations.c src/data.c

    - name: Functional test with small fixtures
      run: |
        # (criares no repositório um ficheiro pass_test.txt com 10 linhas de exemplo)
        ./portagens pass_test.txt > out.txt
        # verifica que lê pelo menos a primeira linha
        grep -q "1) NIF=" out.txt

    - name: Memory check with AddressSanitizer
      run: |
        gcc -g -fsanitize=address -Iinclude -o port_san src/*.c
        ./port_san pass_test.txt
